version: '3.8'

services:
  black-briday-dashboard:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: black-briday-dashboard
    ports:
      - "8502:8501"  # Port host : Port container
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped